print("How old are you?",end=' ')
age = input()
print("How tall are you?",end=' ')
height = input()
print("How much do you weight?",end=' ')
weight = input()

print("So,you're %s old,%s tall and %s heavy."%(age,height,weight))
a = int(input("提示信息"))
print(a)
b = float(input('浮点型的数'))
print(b)
