True or False	"""This should be True"""
False and True	"""This should be False"""
1 == 1 and 2 == 1	"""True and False >>> False"""
"test" = "test"	"""This should True"""
1 ==1 or 2 != 1	"""True or True >>> True"""
True and 1 == 1	"""True and True >>> True"""
False and 0 != 0	"""False and False >>> False"""
True or 1 == 1	"""True or True >>> True"""
"test" == "testing"	"""This is should False"""
1 != 0 and 2 != 1	"""True and True >>> True"""
"test" != "testing"	"""This should be True　"""

